### PR TITLE
Use wp_get_referer instead of $_SERVER['HTTP_REFERER']

### PR DESCRIPTION
**Pull request by dpanta94**
### All Submissions:

* [x] Does your code follow the [Extendables](https://extendomattic.wordpress.com/standardizations/) standards?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changes proposed in this Pull Request:

Changes the approach of confirming if the active Request is an AJAX request. 
@see https://github.com/woocommerce/woocommerce-gateway-amazon-pay/pull/213#discussion_r990416190

### Other information:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### CODE REVIEW

**Review by kalessil — APPROVED** [review]
LGTM!

**Comment by dpanta94** [comment]
@kalessil we can also include this. changes are minors and it has been tested

**Review by kalessil — APPROVED** [review]
LGTM!

**Comment by kalessil** [comment]
@dpanta94: sounds good, approving!

**Pull request merged**
